// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllocatePortRequest {
    /// Hangi çağrı için port istendiği (izlenebilirlik için)
    #[prost(string, tag="1")]
    pub call_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AllocatePortResponse {
    /// Ayrılan çift sayılı RTP portu
    #[prost(uint32, tag="1")]
    pub rtp_port: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReleasePortRequest {
    #[prost(uint32, tag="1")]
    pub rtp_port: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReleasePortResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
}
// @@protoc_insertion_point(module)
