# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiric/dialplan/v1/dialplan.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentiric/dialplan/v1/dialplan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#sentiric/dialplan/v1/dialplan.proto\x12\x14sentiric.dialplan.v1\"6\n\x12GetDialplanRequest\x12\x0e\n\x06to_uri\x18\x01 \x01(\t\x12\x10\n\x08\x66rom_uri\x18\x02 \x01(\t\"\x86\x03\n\x13GetDialplanResponse\x12\x41\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x30.sentiric.dialplan.v1.GetDialplanResponse.Action\x1a\xab\x02\n\x06\x41\x63tion\x12\x43\n\x04type\x18\x01 \x01(\x0e\x32\x35.sentiric.dialplan.v1.GetDialplanResponse.Action.Type\x12T\n\nparameters\x18\x02 \x03(\x0b\x32@.sentiric.dialplan.v1.GetDialplanResponse.Action.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"S\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eROUTE_TO_AGENT\x10\x01\x12\x15\n\x11PLAY_ANNOUNCEMENT\x10\x02\x12\n\n\x06REJECT\x10\x03\x32u\n\x0f\x44ialplanService\x12\x62\n\x0bGetDialplan\x12(.sentiric.dialplan.v1.GetDialplanRequest\x1a).sentiric.dialplan.v1.GetDialplanResponseBJZHgithub.com/sentiric/sentiric-core-interfaces/gen/go/sentiric/dialplan/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiric.dialplan.v1.dialplan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZHgithub.com/sentiric/sentiric-core-interfaces/gen/go/sentiric/dialplan/v1'
  _globals['_GETDIALPLANRESPONSE_ACTION_PARAMETERSENTRY']._loaded_options = None
  _globals['_GETDIALPLANRESPONSE_ACTION_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_GETDIALPLANREQUEST']._serialized_start=61
  _globals['_GETDIALPLANREQUEST']._serialized_end=115
  _globals['_GETDIALPLANRESPONSE']._serialized_start=118
  _globals['_GETDIALPLANRESPONSE']._serialized_end=508
  _globals['_GETDIALPLANRESPONSE_ACTION']._serialized_start=209
  _globals['_GETDIALPLANRESPONSE_ACTION']._serialized_end=508
  _globals['_GETDIALPLANRESPONSE_ACTION_PARAMETERSENTRY']._serialized_start=374
  _globals['_GETDIALPLANRESPONSE_ACTION_PARAMETERSENTRY']._serialized_end=423
  _globals['_GETDIALPLANRESPONSE_ACTION_TYPE']._serialized_start=425
  _globals['_GETDIALPLANRESPONSE_ACTION_TYPE']._serialized_end=508
  _globals['_DIALPLANSERVICE']._serialized_start=510
  _globals['_DIALPLANSERVICE']._serialized_end=627
# @@protoc_insertion_point(module_scope)
