# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiric/user/v1/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentiric/user/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsentiric/user/v1/user.proto\x12\x10sentiric.user.v1\"+\n\x17\x41uthenticateUserRequest\x12\x10\n\x08\x66rom_uri\x18\x01 \x01(\t\"\xdb\x01\n\x18\x41uthenticateUserResponse\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32\x31.sentiric.user.v1.AuthenticateUserResponse.Status\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\"X\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x14\n\x10STATUS_NOT_FOUND\x10\x02\x12\x11\n\rSTATUS_FAILED\x10\x03\x32x\n\x0bUserService\x12i\n\x10\x41uthenticateUser\x12).sentiric.user.v1.AuthenticateUserRequest\x1a*.sentiric.user.v1.AuthenticateUserResponseBFZDgithub.com/sentiric/sentiric-core-interfaces/gen/go/sentiric/user/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiric.user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZDgithub.com/sentiric/sentiric-core-interfaces/gen/go/sentiric/user/v1'
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_start=49
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_end=92
  _globals['_AUTHENTICATEUSERRESPONSE']._serialized_start=95
  _globals['_AUTHENTICATEUSERRESPONSE']._serialized_end=314
  _globals['_AUTHENTICATEUSERRESPONSE_STATUS']._serialized_start=226
  _globals['_AUTHENTICATEUSERRESPONSE_STATUS']._serialized_end=314
  _globals['_USERSERVICE']._serialized_start=316
  _globals['_USERSERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
